# Site settings
baseURL = "https://canstream.github.io/"
languageCode = "en-us"
title = "2019 Community Media Conference"
theme = "forty"
publishDir = "canstream.github.io"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "2019 Community Media Conference"
  description = "Community Media Association"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "2019 Community Media Conference"
    subtitle = "Community Media Association"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Community Media Association"
      url = "https://www.commedia.org.uk"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "2019 Community Media Conference"
    subtitle = "Saturday 28th September, Quay House, BBC MediaCityUK, Salford Quays"
    buttonText = "Start"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Location"
      subtitle = "Directions"
      image = "pic01.jpg"
      url = "pages/location"

    [[params.tiles.showcase]]
      title = "Agenda"
      subtitle = "Timetable"
      image = "pic02.jpg"
      url = "pages/agenda"

    [[params.tiles.showcase]]
      title = "Biographies"
      subtitle = "Speaker details"
      image = "pic03.jpg"
      url = "pages/biogs"

    [[params.tiles.showcase]]
      title = "Sponsors"
      subtitle = "Sponsors & supporters"
      image = "pic04.jpg"
      url = "pages/sponsors"

    [[params.tiles.showcase]]
      title = "Consequat"
      subtitle = "Ipsum Dolor Sit Amet"
      image = "pic05.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Citizen journalism workshop"
      subtitle = "Sunday 29th September"
      image = "pic06.jpg"
      url = "pages/citizen"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Book now"
    subtitle = """Book now for the UK's largest Community Media conference to be held at Quay House, BBC MediaCityUK in Salford on Saturday 28th September - tickets are available below at only £25 per person!

The theme of this year's Conference is "We Need To Talk" to recognise that the community media sector needs to talk to Government, to funders, and to the wider media industry."""
    buttonText = "Book now"
    url = "https://2019cma.eventbrite.co.uk"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "conference@commedia.org.uk"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 (0)114 279 5219"

    [[params.contact.address]]
    title = "Community Media Association"
    street = "The Workstation, 15 Paternoster Row"
    city = "Sheffield S1 2BX"
    #country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Community Media Association"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/community_media"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/CommunityMediaAssociation"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/community_media"
      label = "Instagram"
    
#    [[params.footer.social]]
#      icon = "fa-github"
#      url= "https://www.github.com"
#      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/company/community-media-association"
      label = "LinkedIn"

#    [[params.footer.quicklinks]]
#      text = "Design: "
#      url= "https://www.html5up.net"
#      alt = "HTML5 UP"
